#!/usr/bin/env python3
"""
Topic Tree Temp File Cleanup Script - Safe Temporary File Deletion

This script cleans up temporary files generated by the topic tree validation process.
Uses a whitelist mechanism to ensure only specific files can be deleted, preventing accidental deletion.

Usage:
    python cleanup_topic_tree_temp.py [options]

Options:
    --dry-run     Only show files to be deleted, don't actually delete
    --all         Clean all temp files (match extended whitelist)
    --quiet       Silent mode, no terminal output (still writes to log)
    --help        Show help information

Output Format (JSON):
    {
        "success": true/false,
        "deleted": ["file1.md", "file2.md"],
        "skipped": ["file3.md"],
        "dry_run": true/false,
        "log_file": "ai_workspace/temp/cleanup.log"
    }

Exit Codes:
    0 - Success
    1 - Failure
"""

import argparse
import fnmatch
import json
import os
import sys
from datetime import datetime
from pathlib import Path


# Whitelist files (hardcoded, security boundary)
ALLOWED_FILES = {
    "discussion_topics.md.bak",
    "new_topic_tree.md",
}

# Extended whitelist patterns (--all mode)
EXTENDED_PATTERNS = [
    "*.bak",
    "*.tmp",
]

# Temp directory path relative to script location
TEMP_DIR_RELATIVE = "../ai_workspace/temp"


def get_temp_dir() -> Path:
    """Get absolute path to temp file directory"""
    script_dir = Path(__file__).parent.resolve()
    temp_dir = (script_dir / TEMP_DIR_RELATIVE).resolve()
    return temp_dir


def get_log_file(temp_dir: Path) -> Path:
    """Get log file path"""
    return temp_dir / "cleanup.log"


def write_log(log_file: Path, message: str):
    """Write to log"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}\n"
    
    # Ensure directory exists
    log_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(log_entry)


def is_file_allowed(filename: str, use_extended: bool = False) -> bool:
    """Check if file is in whitelist"""
    # Check basic whitelist
    if filename in ALLOWED_FILES:
        return True
    
    # If using extended mode, check extended whitelist
    if use_extended:
        for pattern in EXTENDED_PATTERNS:
            if fnmatch.fnmatch(filename, pattern):
                return True
    
    return False


def cleanup_temp_files(
    dry_run: bool = False,
    use_all: bool = False,
    quiet: bool = False
) -> dict:
    """
    Clean up temporary files
    
    Args:
        dry_run: Whether to preview only without actual deletion
        use_all: Whether to use extended whitelist
        quiet: Whether to use silent mode
    
    Returns:
        dict: Dictionary containing cleanup results
    """
    temp_dir = get_temp_dir()
    log_file = get_log_file(temp_dir)
    
    result = {
        "success": True,
        "deleted": [],
        "skipped": [],
        "dry_run": dry_run,
        "log_file": str(log_file.relative_to(temp_dir.parent.parent))
    }
    
    # Check if directory exists
    if not temp_dir.exists():
        # Directory doesn't exist, create it and return success (nothing to delete)
        temp_dir.mkdir(parents=True, exist_ok=True)
        write_log(log_file, "INIT: Created temp directory (was missing)")
        return result
    
    # Iterate through files in directory
    for item in temp_dir.iterdir():
        if not item.is_file():
            continue
        
        filename = item.name
        
        # Skip log file itself
        if filename == "cleanup.log":
            continue
        
        # Check if in whitelist
        if is_file_allowed(filename, use_all):
            if dry_run:
                result["deleted"].append(filename)
                write_log(log_file, f"DRY-RUN: Would delete {filename}")
            else:
                try:
                    item.unlink()
                    result["deleted"].append(filename)
                    write_log(log_file, f"DELETED: {filename}")
                except Exception as e:
                    result["skipped"].append(filename)
                    result["success"] = False
                    write_log(log_file, f"ERROR: Failed to delete {filename}: {e}")
        else:
            result["skipped"].append(filename)
            write_log(log_file, f"SKIPPED: {filename} (not in whitelist)")
    
    return result


def main():
    """Main function"""
    parser = argparse.ArgumentParser(
        description="Clean up temporary files generated by topic tree validation process",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Safety Mechanisms:
  - Whitelist restriction: Can only delete predefined filenames (hardcoded)
  - Path restriction: Can only operate on ai_workspace/temp/ directory
  - No arbitrary path exposure: Cannot delete other files through parameters

Examples:
  python cleanup_topic_tree_temp.py              # Basic cleanup
  python cleanup_topic_tree_temp.py --dry-run    # Preview mode
  python cleanup_topic_tree_temp.py --all        # Extended cleanup
  python cleanup_topic_tree_temp.py --quiet      # Silent mode
        """
    )
    
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only show files to be deleted, don't actually delete"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Clean all temp files (match extended whitelist *.bak, *.tmp)"
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Silent mode, no terminal output (still writes to log)"
    )
    
    args = parser.parse_args()
    
    # Execute cleanup
    result = cleanup_temp_files(
        dry_run=args.dry_run,
        use_all=args.all,
        quiet=args.quiet
    )
    
    # Output result
    if not args.quiet:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    
    # Return exit code
    sys.exit(0 if result["success"] else 1)


if __name__ == "__main__":
    main()
